name: Cypress
on: [push]
jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-18.04
    env:
      MAAS_PORT: 9000
    steps:
      - uses: actions/checkout@main
      - name: Set environment variables
        run: echo "::set-env name=IP_ADDRESS::$(hostname -I | cut -d" " -f1)"
      - name: Install MAAS
        run: |
          sudo systemctl enable snapd
          sudo snap install maas --channel=latest/edge
          sudo snap install maas-test-db
      - name: Initialise MAAS
        run: |
          sudo maas init region+rack \
            --maas-url=http://${{env.IP_ADDRESS}}:${{env.MAAS_PORT}}/MAAS \
            --database-uri maas-test-db:///
      - name: Create MAAS admin
        run: sudo maas createadmin --username=admin --password=test --email=fake@example.org
      - name: Start MAAS
        run: sudo snap start maas
      - name: Curl maas
        run: curl http://${{env.IP_ADDRESS}}:${{env.MAAS_PORT}}/MAAS/r/machines
      - uses: cypress-io/github-action@master
        with:
          working-directory: proxy
          config: baseUrl=http://${{env.IP_ADDRESS}}:${{env.MAAS_PORT}},pageLoadTimeout=100000
          wait-on: "http://${{env.IP_ADDRESS}}:${{env.MAAS_PORT}}/MAAS/r/machines"
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
